version: "3"
services:
  server:
    build: backend/
    image: solar1s/backend:0.0.2
    ports:
      - 8080:8080

  client:
    build: frontend/
    image: solar1s/frontend:0.0.2
    ports:
      - 3000:3000

    # дождаться сервера
    depends_on:
      - server